### ISSUE TITLE
First open T&C Agreement Unreadable

### ISSUE THREAD

**Issue by sanctimoniousape** [pyamsoft/tetherfi#289] opened 2024-04-28 21:32 UTC
I installed this from Izzy to avoid the Google tracking, but was still prompted for this anyway.

As can be seen in the attached screenshot, the text is cut off, and the dialog box is not scrollable so I'm unable to see the entirety of what I'm supposed to be agreeing to.  I know they're less common nowadays, but low resolution & small screen devices need to be allowed for - especially for legalese.

Not that I want to agree to Google tracking anyway. Speaking of which, I searched my settings and could not find anything about "Vitals" in order to disable it.  Please be more specific about how to disable it.

![Screenshot_20240428-172235](https://github.com/pyamsoft/tetherfi/assets/80165446/b77e34a0-e6ad-44f7-a6fc-044b6655f6ef)

**Comment by pyamsoft** [comment] 2024-04-28 22:17
Hi, I'm currently working on a visual refresh to support smaller screens, I hope to be able to release it soon!

Vitals are what google calls the "Usage and Diagnostics" setting in android system settings. You can disable them there.

TetherFi includes zero tracking, but we are not able to see or modify this system level setting. For people who dislike tracking, this dialog was intended to let them know.

**Comment by pyamsoft** [comment] 2024-04-28 22:19
Also that dialog has been scrollable for the last few releases. I don't know what version the Izzy repo is distributing, as I only can officially support the Google play store, but that screen is meant to scroll to avoid small-screen situations like yours. Sorry about that :(

**Comment by pyamsoft** [comment] 2024-05-02 02:12
Hello, the latest changes in the (currently beta) version 41 have adjusted some things to better support small screen devices. Unfortunately, I do not have a small screen device in real life, so I have to test on the Android Studio Emulator with a small screen (4.6") device.

The dialog should scroll with the latest version, hopefully when this release is made stable, it will be better for your device. Thanks!

**Comment by pyamsoft** [comment] 2024-05-04 19:06
Hi, some visual bugs were still noticed in version 41. I hope to release a quick follow up version 42 which will actually, for real this time, hopefully solve this :)

I also have reworded the screen to better convey that TetherFi does no tracking of any kind, and that the warning screen is for Android system related crash reporting.

Thanks for the continued patience.

**Comment by pyamsoft** [comment] 2024-06-28 04:05
With the release of version 43, this bug should be fixed, and that dialog should be scrollable on small screen devices.

Thank you for your contribution to the project!

**Closed** 2024-06-29 14:34 UTC
Labels: bug, compatibility
