### ISSUE TITLE
No internet access in a lot of applications

### ISSUE THREAD

**Issue by MohammedALShimmary** [pyamsoft/tetherfi#330] opened 2024-09-12 11:00 UTC
![IMG-20240912-WA0012](https://github.com/user-attachments/assets/db79dc85-202b-4202-9311-4c55b1a3393d)
![Screenshot_20240912_135309](https://github.com/user-attachments/assets/dc54241c-867d-444c-a0fa-9ee8fddbcc0c)
![Screenshot_20240912_135226](https://github.com/user-attachments/assets/e2b73d9b-c4f9-4889-b03f-89932301ab03)
![Screenshot_20240912_135208](https://github.com/user-attachments/assets/c1db62d9-b65c-4971-9ac4-492e356d4e96)

I'm having internet issues , where a lot of apps have no internet connection.
I'm using my Red Magic 5G as the tethering device and my Red Magic 8 Pro as the client.

You can see in the attachment, I set the Proxy per the instructions, but telegram is not even connecting and pinging 8.8.8.8 is not working.

I'm also wondering about the instructions as it is saying ( http & https ) proxy need to be added while my Red Magic 8 Pro has only one setting as per the attached screen. is this related ?

Other apps like "NeShare" are using some sort of  fake VPN server ( or local VPN , whatever it is called ) and the internet connection works okay ( kind of ). But i want to use yours because it has Bandwidth Limit function.

**Comment by pyamsoft** [comment] 2024-09-12 14:11
Hi

Ping does not work when using the proxy as it doesn't implement ICMP

I believe these network issues are caused by a still buggy implementation of bandwidth limiting. I will close this issue in favor of your other one and we can troubleshoot there instead. I hope that is okay.

**Closed** 2024-09-12 14:11 UTC
Labels: bug, duplicate
